### ISSUE TITLE
Comparisons with the official React-Redux library?

### ISSUE THREAD

**Issue by markerikson** [arnemahl/react-redux-subscribe-while-mounted#2]
I'm kind of curious.  What specific benefits does this have over the `connect` method provided by the official [React-Redux](https://github.com/reactjs/react-redux) library?  Also, the examples you give for "vanilla Redux" show components manually subscribing to the store, but there's no reason to do that given that `connect` manages store subscriptions for you.

**Comment by arnemahl** [comment]
Hi Mark, thanks for taking an interest in this project.

As [React-Redux](https://github.com/reactjs/react-redux) is a separate package, albeit an official one, I don't consider it part of "vanilla" React/Redux. In projects where one is already using `connect` (from React-Redux) you are right to assume that there is no added benefit of using `subscribeWhileMounted` (from this package) in addition.

I created this package to use in a couple of projects where we were using React and Redux _without_ `connnect`. We might switch all the way over to using `connect` instead of `subscribeWhileMounted`, but at the time it seemed like a smaller transition to just use `subscribeWhileMounted` instead of `subcribe`.

I have yet to weigh the two against each other, but the original idea was that `subscribeWhileMounted` might be an easier-to-grasp alternative to `connect`, with fewer layers of abstraction.

Again, thanks for your input :)

**Comment by markerikson** [comment]
Ah... React-Redux _is_ the official library for integrating React and Redux together.  Dan wrote it, the official Redux docs talk about using it, it's part of the same Github org and run by the same group of maintainers, and all the examples use it.

You are certainly not _required_ to use `connect` if you don't want to, and there are indeed some alternative UI/subscription integration packages out there already, but unless you have some very specific requirements I'm not really sure what benefits building your own library gives you.  There's been a _lot_ of optimization work that's gone into `connect` (and even more with the v5 beta version).  

FYI, at a conceptual level `connect` is relatively simple.  It creates a wrapper component that subscribes to the store, runs a "selector"-type function to extract some portion of data from the state, and if any of that data has changed, re-renders the "real" component and passes the extracted data in as props.  Dan wrote up a great miniature version of `connect` to illustrate the approach: https://gist.github.com/gaearon/1d19088790e70ac32ea636c025ba424e .  The real version of `connect` is decidedly more complex internally due to optimization work, but that's the basic idea right there.

Again, you're definitely welcome to keep using your own library if you want, but you may be losing out on perf benefits and shared usage network effects (docs, etc) if you do.

**Comment by arnemahl** [comment]
Ok, I'll update the readme and point out that React-Redux should definitely be considered before using this utility.
